### PR TITLE
CIRCLE-6932 added AWS permissions for managing volumes

### PR DESCRIPTION
**Pull request by smaant**

### CODE REVIEW

**Comment by notnoopci** [comment]
lgtm

**Comment by diranged** [comment]
Would you guys mind updating the doc/docstrings here to indicate what these permissions are used for - is this somerthing coming in an upcoming enterprise release?

**Comment by smaant** [comment]
@diranged unfortunately, AWS policies are in JSON format so we can't add docstrings right into the template (which would be ideal) but we will figure out where to document it, thank you. Volumes permissions are required for an upcoming feature, correct.

**Comment by diranged** [comment]
@smaant, I have implemented the same changes in our CFN stack at https://github.com/circleci/enterprise-setup/pull/56/commits/e0c006ee9c5896a44eb822474449f00ef18022ba... let me know if they look good?

**Pull request merged**
